/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BrandStrategyRouteImport } from './routes/brand-strategy'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesReputationMediaRouteImport } from './routes/services.reputation-media'
import { Route as ServicesExecutivePersonalBrandingRouteImport } from './routes/services.executive-personal-branding'
import { Route as ServicesEventsExperientialMarketingRouteImport } from './routes/services.events-experiential-marketing'
import { Route as ServicesDigitalPublicAffairsRouteImport } from './routes/services.digital-public-affairs'
import { Route as ServicesCreativeProductionRouteImport } from './routes/services.creative-production'
import { Route as ServicesContentSocialRouteImport } from './routes/services.content-social'
import { Route as ServicesAuthorPublishingRouteImport } from './routes/services.author-publishing'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStrategyRoute = BrandStrategyRouteImport.update({
  id: '/brand-strategy',
  path: '/brand-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReputationMediaRoute = ServicesReputationMediaRouteImport.update({
  id: '/reputation-media',
  path: '/reputation-media',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesExecutivePersonalBrandingRoute =
  ServicesExecutivePersonalBrandingRouteImport.update({
    id: '/executive-personal-branding',
    path: '/executive-personal-branding',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesEventsExperientialMarketingRoute =
  ServicesEventsExperientialMarketingRouteImport.update({
    id: '/events-experiential-marketing',
    path: '/events-experiential-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDigitalPublicAffairsRoute =
  ServicesDigitalPublicAffairsRouteImport.update({
    id: '/digital-public-affairs',
    path: '/digital-public-affairs',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCreativeProductionRoute =
  ServicesCreativeProductionRouteImport.update({
    id: '/creative-production',
    path: '/creative-production',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesContentSocialRoute = ServicesContentSocialRouteImport.update({
  id: '/content-social',
  path: '/content-social',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAuthorPublishingRoute =
  ServicesAuthorPublishingRouteImport.update({
    id: '/author-publishing',
    path: '/author-publishing',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/contact-us': typeof ContactUsRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/services/author-publishing': typeof ServicesAuthorPublishingRoute
  '/services/content-social': typeof ServicesContentSocialRoute
  '/services/creative-production': typeof ServicesCreativeProductionRoute
  '/services/digital-public-affairs': typeof ServicesDigitalPublicAffairsRoute
  '/services/events-experiential-marketing': typeof ServicesEventsExperientialMarketingRoute
  '/services/executive-personal-branding': typeof ServicesExecutivePersonalBrandingRoute
  '/services/reputation-media': typeof ServicesReputationMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/contact-us': typeof ContactUsRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/services/author-publishing': typeof ServicesAuthorPublishingRoute
  '/services/content-social': typeof ServicesContentSocialRoute
  '/services/creative-production': typeof ServicesCreativeProductionRoute
  '/services/digital-public-affairs': typeof ServicesDigitalPublicAffairsRoute
  '/services/events-experiential-marketing': typeof ServicesEventsExperientialMarketingRoute
  '/services/executive-personal-branding': typeof ServicesExecutivePersonalBrandingRoute
  '/services/reputation-media': typeof ServicesReputationMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/contact-us': typeof ContactUsRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/services/author-publishing': typeof ServicesAuthorPublishingRoute
  '/services/content-social': typeof ServicesContentSocialRoute
  '/services/creative-production': typeof ServicesCreativeProductionRoute
  '/services/digital-public-affairs': typeof ServicesDigitalPublicAffairsRoute
  '/services/events-experiential-marketing': typeof ServicesEventsExperientialMarketingRoute
  '/services/executive-personal-branding': typeof ServicesExecutivePersonalBrandingRoute
  '/services/reputation-media': typeof ServicesReputationMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/brand-strategy'
    | '/contact-us'
    | '/packages'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/services/author-publishing'
    | '/services/content-social'
    | '/services/creative-production'
    | '/services/digital-public-affairs'
    | '/services/events-experiential-marketing'
    | '/services/executive-personal-branding'
    | '/services/reputation-media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/brand-strategy'
    | '/contact-us'
    | '/packages'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/services/author-publishing'
    | '/services/content-social'
    | '/services/creative-production'
    | '/services/digital-public-affairs'
    | '/services/events-experiential-marketing'
    | '/services/executive-personal-branding'
    | '/services/reputation-media'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/brand-strategy'
    | '/contact-us'
    | '/packages'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/services/author-publishing'
    | '/services/content-social'
    | '/services/creative-production'
    | '/services/digital-public-affairs'
    | '/services/events-experiential-marketing'
    | '/services/executive-personal-branding'
    | '/services/reputation-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BrandStrategyRoute: typeof BrandStrategyRoute
  ContactUsRoute: typeof ContactUsRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-strategy': {
      id: '/brand-strategy'
      path: '/brand-strategy'
      fullPath: '/brand-strategy'
      preLoaderRoute: typeof BrandStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reputation-media': {
      id: '/services/reputation-media'
      path: '/reputation-media'
      fullPath: '/services/reputation-media'
      preLoaderRoute: typeof ServicesReputationMediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/executive-personal-branding': {
      id: '/services/executive-personal-branding'
      path: '/executive-personal-branding'
      fullPath: '/services/executive-personal-branding'
      preLoaderRoute: typeof ServicesExecutivePersonalBrandingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/events-experiential-marketing': {
      id: '/services/events-experiential-marketing'
      path: '/events-experiential-marketing'
      fullPath: '/services/events-experiential-marketing'
      preLoaderRoute: typeof ServicesEventsExperientialMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/digital-public-affairs': {
      id: '/services/digital-public-affairs'
      path: '/digital-public-affairs'
      fullPath: '/services/digital-public-affairs'
      preLoaderRoute: typeof ServicesDigitalPublicAffairsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/creative-production': {
      id: '/services/creative-production'
      path: '/creative-production'
      fullPath: '/services/creative-production'
      preLoaderRoute: typeof ServicesCreativeProductionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content-social': {
      id: '/services/content-social'
      path: '/content-social'
      fullPath: '/services/content-social'
      preLoaderRoute: typeof ServicesContentSocialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/author-publishing': {
      id: '/services/author-publishing'
      path: '/author-publishing'
      fullPath: '/services/author-publishing'
      preLoaderRoute: typeof ServicesAuthorPublishingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAuthorPublishingRoute: typeof ServicesAuthorPublishingRoute
  ServicesContentSocialRoute: typeof ServicesContentSocialRoute
  ServicesCreativeProductionRoute: typeof ServicesCreativeProductionRoute
  ServicesDigitalPublicAffairsRoute: typeof ServicesDigitalPublicAffairsRoute
  ServicesEventsExperientialMarketingRoute: typeof ServicesEventsExperientialMarketingRoute
  ServicesExecutivePersonalBrandingRoute: typeof ServicesExecutivePersonalBrandingRoute
  ServicesReputationMediaRoute: typeof ServicesReputationMediaRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAuthorPublishingRoute: ServicesAuthorPublishingRoute,
  ServicesContentSocialRoute: ServicesContentSocialRoute,
  ServicesCreativeProductionRoute: ServicesCreativeProductionRoute,
  ServicesDigitalPublicAffairsRoute: ServicesDigitalPublicAffairsRoute,
  ServicesEventsExperientialMarketingRoute:
    ServicesEventsExperientialMarketingRoute,
  ServicesExecutivePersonalBrandingRoute:
    ServicesExecutivePersonalBrandingRoute,
  ServicesReputationMediaRoute: ServicesReputationMediaRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BrandStrategyRoute: BrandStrategyRoute,
  ContactUsRoute: ContactUsRoute,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
